# Generated by Django 4.2.7 on 2026-01-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Teachify", max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex Code like #000000",
                        max_length=7,
                    ),
                ),
                ("secondary_color", models.CharField(default="#6c757d", max_length=7)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
