# Generated by Django 4.2.7 on 2026-01-25 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Email Verified At"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_attempts",
            field=models.IntegerField(default=0, verbose_name="Verification Attempts"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Verification Token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Token Expires At"
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(db_index=True, max_length=255)),
                ("verified", models.BooleanField(default=False)),
                ("attempt_count", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="accounts_em_token_d0a1b9_idx"),
                    models.Index(
                        fields=["user", "verified"],
                        name="accounts_em_user_id_191379_idx",
                    ),
                ],
            },
        ),
    ]
