# Generated by Django 4.2.7 on 2026-01-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_email_verified_at_user_verification_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationlog",
            name="otp",
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
    ]
